import streamlit as st
import pandas as pd

# 1. Page Config
st.set_page_config(
    page_title="CFB Quant Engine",
    page_icon="🏈",
    layout="wide"
)

# 2. Title & Header
st.title("🏈 CFB Algorithmic Betting Engine")
st.markdown("### Powered by Decay Metrics, SRS, and Talent Composites")

# 3. Load Data
# We use a function with @st.cache_data so it stays fast
@st.cache_data
def load_data():
    try:
        # Load the CSV generated by your pipeline
        df = pd.read_csv("live_predictions.csv")
        
        # Convert 'Conf' percentage string to float for sorting/coloring
        # e.g., "58.6%" -> 0.586
        df['Confidence_Score'] = df['Conf'].str.rstrip('%').astype(float) / 100.0
        return df
    except FileNotFoundError:
        return pd.DataFrame()

df = load_data()

if df.empty:
    st.error("No predictions found. Please run the pipeline locally and push the CSV.")
else:
    # 4. KPI Metrics (The "Green Light" Plays)
    st.divider()
    st.subheader("💰 The Alpha Plays (>55% Confidence)")
    
    # Filter for high confidence
    alpha_plays = df[df['Confidence_Score'] > 0.55].copy()
    
    if not alpha_plays.empty:
        # Display Alpha Plays as Metric Cards
        cols = st.columns(min(len(alpha_plays), 4)) # Create dynamic columns
        for index, (i, row) in enumerate(alpha_plays.iterrows()):
            # Cycle through columns
            col = cols[index % 4]
            with col:
                st.metric(
                    label=f"{row['Game']} ({row['Spread']})",
                    value=row['Pick'],
                    delta=row['Conf']
                )
    else:
        st.info("No Alpha Plays found for this week. Staying disciplined.")

    # 5. Full Data Table
    st.divider()
    st.subheader("📋 Full Betting Card")

    # Color code the confidence column
    # Green for high confidence, Red for low
    def color_confidence(val):
        color = 'white'
        if val > 0.60:
            color = '#4CAF50' # Strong Green
        elif val > 0.55:
            color = '#8BC34A' # Light Green
        elif val < 0.53:
            color = '#FF5252' # Red
        return f'background-color: {color}; color: black'

    # Display interactive table
    # We hide the helper column 'Confidence_Score'
    st.dataframe(
        df.style.map(color_confidence, subset=['Confidence_Score']),
        column_config={
            "Confidence_Score": None # Hide this internal column
        },
        use_container_width=True,
        hide_index=True
    )

    # 6. Sidebar (Methodology)
    with st.sidebar:
        st.header("⚙️ Model Logic")
        st.write("""
        **Strategy:**
        * **Leak-Proof:** No season-long stat leaks.
        * **Smart Decay:** Exponential weighted momentum.
        * **Context:** SRS Power Ratings + Talent Composite.
        
        **Legend:**
        * 🟢 **>60%:** Max Bet (1.5u)
        * 🟢 **>55%:** Standard Bet (1.0u)
        * 🔴 **<53%:** Pass (No Edge)
        """)
        st.caption("Updated via Local Pipeline")